# Generated by Django 6.0.2 on 2026-02-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['street_name'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='street_name',
        ),
    ]
