# Generated by Django 6.0.2 on 2026-02-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='streetsuffix',
            new_name='street_suffix',
        ),
    ]
